server:
  port: 8585

spring:
  application:
    name: Press-lab

  datasource:
    url: jdbc:postgresql://dpg-cprefplumphs73c448dg-a:5432/presslab
    username: presslab_user
    password: c8KBCw2vAy2d24YncSW3F9ojBb4UXxQV
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/presslab?createDatabaseIfNotExist=true
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: orxanrustamov1827@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#spring:
#  application:
#      name: Press-lab
#  datasource:
#    url: jdbc:mysql://localhost:3306/presslab
#    username: root
#    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jakarta:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
